### ISSUE TITLE
请问如何安装ipk软件包

### ISSUE THREAD

**Issue by tl656565** [aoxueos/OpenWrtBuild_Occupied#2]
小白发文，通过文件传输功能上传luci-app-ipsec-vpnserver-manyusers_git-23.361.56158-91729a3_all.ipk到tmp文件夹，安装后提示安装成功。但是找不到功能入口，可否指导下

**Comment by wpsdoo** [comment]
> 小白发文，通过文件传输功能上传luci-app-ipsec-vpnserver-manyusers_git-23.361.56158-91729a3_all.ipk到tmp文件夹，安装后提示安装成功。但是找不到功能入口，可否指导下

**Comment by wpsdoo** [comment]
使用软件包安装，需要界面管理的app 需要安装luci-app 文件 安装完成后，刷新页面
